name: justdataanno
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.10
 - pip
 - pip:
   - streamlit
   - requests
   - pyyaml
   - sqlalchemy
   - streamlit_tags
   - datasets
   - cryptography
   - langchain
   - langchain-core
   - langchain-community
   - langchain_experimental
   - markdown-it-py
   - numpy
   - pandas
   - pyarrow
   - tabulate
   - Werkzeug
   - openai
   - huggingface-hub
   - jsonschema